name: test
on:
  push:
    branches:
      - main

jobs:
  run:
    name: Setup seal
    runs-on: ubuntu-latest
    steps:
      - uses: 010DevX101/setup-seal@v0.0.1-rc.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Run
        run: seal run
