name: test
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Setup seal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 010DevX101/setup-seal@v0.0.1-rc.13
        with:
          version: v0.0.5-rc.2
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run
        run: seal run
